include(FetchContent)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF)
set(ENABLE_SAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_OPENMP OFF CACHE BOOL "" FORCE)
set(ENABLE_WIDE_CHAR OFF CACHE BOOL "" FORCE)
set(KISSFFT_STATIC ON CACHE BOOL "" FORCE)
set(KISSFFT_DATATYPE double CACHE STRING "" FORCE)
set(KISSFFT_TEST OFF CACHE BOOL "" FORCE)
set(KISSFFT_TOOLS OFF CACHE BOOL "" FORCE)
set(KISSFFT_PKGCONFIG OFF CACHE BOOL "" FORCE)
set(JSON_BuildTests OFF CACHE BOOL "" FORCE)
FetchContent_Declare(muparser
    URL https://codeload.github.com/beltoforion/muparser/tar.gz/508cce97d983c4c61099ceacc11c984a60053967)
FetchContent_Declare(kissfft
    URL https://codeload.github.com/mborgerding/kissfft/tar.gz/e5e3fac46e0d94a8f8170c06706b7a4218828333)
FetchContent_Declare(nlohmann_json
    URL https://codeload.github.com/nlohmann/json/tar.gz/65ee68451d8eb2b5f3a30b410476ab83deb3289b)
FetchContent_MakeAvailable(muparser kissfft nlohmann_json)
set_target_properties(muparser kissfft PROPERTIES POSITION_INDEPENDENT_CODE ON)
add_library(graph_core STATIC
    ${CMAKE_CURRENT_LIST_DIR}/../core/math.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../core/document.cpp)
target_compile_features(graph_core PUBLIC cxx_std_20)
target_include_directories(graph_core PUBLIC ${CMAKE_CURRENT_LIST_DIR}/../core)
target_link_libraries(graph_core PUBLIC muparser kissfft nlohmann_json::nlohmann_json)
set_target_properties(graph_core PROPERTIES POSITION_INDEPENDENT_CODE ON)
if (EMSCRIPTEN)
    target_compile_options(muparser PRIVATE -fexceptions)
    target_compile_options(graph_core PRIVATE -fexceptions)
endif ()
if(MSVC)
    target_compile_options(graph_core PRIVATE /utf-8)
endif()
